### ISSUE TITLE
0 interactions between 0 nodes

### ISSUE THREAD

**Issue by marieBvr** [saezlab/pypath#21]
Hello,

I am new to pypath so I am trying to run Quick start 1 and 2.
I installed pypath successfully.
I tried running :

```
import pypath
pa = pypath.PyPath()
pa.load_resources({'signor': pypath.data_formats.pathway['signor']})
```

But I obtain : 
```
0 interactions between 0 nodes
 from 0 resources have been loaded,
 for details see the log: ./log/6o011.log
```

The log is like : 

> [2018-07-09 10:54:02] ### INFO ### Logger initialized, logging to log/6o011.log
> [2018-07-09 10:54:02] ### INFO ### PyPath has been initialized
> [2018-07-09 10:54:02] ### INFO ### Beginning session '6o011'
> [2018-07-09 10:54:04] ### INFO ###### Retrieving data by dataio.signor_interactions() ...
> [2018-07-09 10:54:12] ### INFO ### Loading mapping tables...
> [2018-07-09 10:54:12] ### INFO ###### Loading table ('uniprot-sec', 'uniprot-pri') ...
> [2018-07-09 10:54:13] ### INFO ###### Table ('uniprot-sec', 'uniprot-pri') loaded from FileMapping.
> [2018-07-09 10:54:13] ### INFO ### Loading mapping tables...
> [2018-07-09 10:54:13] ### INFO ###### Loading table ('genesymbol', 'trembl') ...
> [2018-07-09 10:54:14] ### INFO ###### Table ('genesymbol', 'trembl') loaded from UniprotMapping.
> [2018-07-09 10:54:14] ### INFO ### Loading mapping tables...
> [2018-07-09 10:54:14] ### INFO ###### Loading table ('genesymbol', 'swissprot') ...
> [2018-07-09 10:54:14] ### INFO ###### Table ('genesymbol', 'swissprot') loaded from UniprotMapping.
> [2018-07-09 10:54:14] ### INFO ### Loading mapping tables...
> [2018-07-09 10:54:14] ### INFO ###### Loading table ('genesymbol-syn', 'swissprot') ...
> [2018-07-09 10:54:15] ### INFO ###### Table ('genesymbol-syn', 'swissprot') loaded from UniprotMapping.
> [2018-07-09 10:54:15] ### INFO ###### 19910 lines have been read from signor_interactions,10098 links after mapping; 
> 		3912 lines filtered by filters;
> 		692 lines filtered because lack of references;
> 		3062 lines filtered by taxon filters.
> [2018-07-09 10:54:15] ### INFO ###### New nodes have been created
> [2018-07-09 10:54:15] ### INFO ###### New edges have been created
> [2018-07-09 10:54:15] ### INFO ###### Introducing new node and edge attributes...
> [2018-07-09 10:54:19] ### WARNING ###### Vertex attribute `exp` has only None values
> [2018-07-09 10:54:19] ### WARNING ###### Edge attribute `negative` has only None values
> [2018-07-09 10:54:19] ### WARNING ###### Edge attribute `negative_refs` has only None values
> [2018-07-09 10:54:19] ### INFO ### Removing duplicate edges...
> [2018-07-09 10:54:19] ### INFO ### Loading mapping tables...
> [2018-07-09 10:54:19] ### INFO ###### Loading table ('genesymbol', 'uniprot') ...
> [2018-07-09 10:54:19] ### INFO ###### Table ('genesymbol', 'uniprot') loaded from UniprotMapping.

What am I doing wrong ?

Marie

**Comment by deeenes** [comment]
Hi Marie,

Thanks a lot for reporting this.
At certain queries UniProt does not accept any more POST but only GET.
Fixed in 0.7.87.

Best wishes,

Denes

**Comment by marieBvr** [comment]
Hi Denes,

I am sorry to re-open this issue but how can I retrieve the changes ?
I tried to re-install pypath but I still have the same errors...

Best wishes,
Marie

**Comment by deeenes** [comment]
Hi Marie,

Make sure you updated the pypath module:

pip3 install --upgrade http://pypath.omnipathdb.org/releases/latest/pypath-latest.tar.gz

Have you already tried this?

Maybe a wrong file remained in the cache? What if you turn off the cache:

`
import pypath
from pypath import curl

pa = pypath.PyPath()

with curl.cache_off():
   pa.load_resources({'signor': pypath.data_formats.pathway['signor']})
`
If this works and you don't have many things in the cache you can maybe empty it entirely, or with the `pypath.curl.cache_print_on` context find out which file is to be deleted or do something like this to delete the specific file:

`
from pypath import curl
from pypath import uniprot_input

with curl.cache_delete_on():
    try:
        uniprot_input.all_uniprots()
    except AttributeError:
        pass
    try:
        uniprot_input.all_uniprots(swissprot = True)
    except AttributeError:
        pass
`

I hope it helps, please tell me if still does not work.

Best,

Denes

**Comment by marieBvr** [comment]
Hi Denes,
I tried pip3 install --upgrade http://pypath.omnipathdb.org/releases/latest/pypath-latest.tar.gz.
 and turn off the cache and it works !
Thank you ! 
Should I turn off the cache every time or do you think it should be all right ?

Thanks again !

Best,
Marie

**Comment by deeenes** [comment]
Hi Marie,

You should not turn it off every time because then it downloads everything each time what takes quite long. `cache_off` is only for the purpose to test if the problem is with some cache file. You should get rid of the wrong cache file. For this either you use the `cache_print_on` context which prints the name of the cache file and then you can delete it. Or use the `cache_delete_on` context to delete the file. I have shown this above with the `all_uniprots` method, because I think that one is the troublemaker at you.

Best,

Denes

**Comment by marieBvr** [comment]
Thank you for the explanations.
I will do as you advise.

Best,
Marie
